# Site settings
title: KnapsackPro.com Documentation
description: > # this means to ignore newlines until "baseurl:"
  Documentation for Knapsack Pro API and tool.
  Optimal test suite parallelization. Speed up tests on CI servers.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://docs.knapsackpro.com" # the base hostname & protocol for your site
knapsack_pro_url: https://knapsackpro.com
twitter_username: KnapsackPro
github_username: KnapsackPro
github_repository: https://github.com/KnapsackPro/docs.knapsackpro.com

# Build settings
markdown: kramdown
